HW #5 — Develop
IvanenkosNatashos/cv pull request #1
Opened 2022-10-05 18:06 UTC by IvanenkosNatashos

2022-10-05 18:20 UTC, a1exalexander requested changes
```
html
    head
    body
```

и никак иначе
есть html и в нем только head и body

2022-10-05 18:20 UTC, a1exalexander commented on index.html
> +</style>
Стили или удали или перенеси внутрь тега `head`

```suggestion
    <style>
        body {width: 600px; font-family: 'Times New Roman', Times, serif;}
        h1 {margin-left: 64px; margin-top: 48px;}
        h2 {margin-left: 64px; margin-top: 12px; margin-bottom: 24px;}
        h3 {margin-left: 64px; margin-top: 24px;}
        h4 {margin-left: 64px; margin-top: 1px; margin-bottom: 8;}
        p {margin-left: 64px;}
        a {margin-left: 64px; margin-top: 12px;}
    </style>
</head>
```

2022-10-05 18:22 UTC, a1exalexander commented
и у тебя тут конфликты( нужно выполнить команду, находясь на ветке `develop`
```bash
git merge origin/main
```

2022-10-05 18:29 UTC, IvanenkosNatashos commented
@a1exalexander вроде, все поправила

конфликт устанила

2022-10-06 09:31 UTC, a1exalexander approved these changes

2022-10-06 09:32 UTC, merged